FLAGS = -Wall -Wextra -Werror -g -lm -lcheck -lsubunit -lrt -lpthread -std=c99
COMP = gcc

ex9: main.c
	$(COMP) main.c ../SystemErrors/errors.c ../vector/intvector.c ../vector/stringvector.c ex9.c test.c  $(FLAGS) -o ex9.a
